theme = "gruvbox_material_dark_hard"

[editor.soft-wrap]
enable = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = false  # Inlay hints are expensive with gopls

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
